<?php

namespace EasyCorp\Bundle\EasyAdminBundle\Icon;

/**
 * Finds the SVG file of FontAwesome Free icons from the CSS classes used to
 * display them with the FontAwesome webfont (e.g. 'fa-solid fa-user', 'far fa-clock',
 * 'fa fa-file-text-o', etc.). The SVG files are generated by the
 * src/Resources/bin/build-fontawesome-icons.php script.
 *
 * @internal
 *
 * @author Javier Eguiluz <javier.eguiluz@gmail.com>
 */
final class FontAwesomeIconResolver
{
    private const ICONS_DIR = __DIR__.'/../../assets/icons/fontawesome';

    private const STYLE_CLASSES = [
        'fas' => FontAwesomeStyle::Solid,
        'fa-solid' => FontAwesomeStyle::Solid,
        'far' => FontAwesomeStyle::Regular,
        'fa-regular' => FontAwesomeStyle::Regular,
        'fab' => FontAwesomeStyle::Brands,
        'fa-brands' => FontAwesomeStyle::Brands,
    ];

    // these classes select the family of the icon but not its style
    private const FAMILY_CLASSES = ['fa', 'fa-classic'];

    // styles and families only available in FontAwesome Pro and kits; the
    // icons that use them are rendered with the FontAwesome CSS loaded by the app
    private const PRO_CLASSES = ['fal', 'fa-light', 'fat', 'fa-thin', 'fad', 'fadr', 'fadl', 'fadt', 'fass', 'fasr', 'fasl', 'fast', 'fasds', 'fak', 'fakd'];
    private const PRO_CLASS_PREFIXES = ['fa-duotone', 'fa-sharp', 'fa-kit'];

    private const MODIFIER_CLASSES = [
        'fa-fw', 'fa-xs', 'fa-sm', 'fa-lg', 'fa-xl', 'fa-2xs', 'fa-2xl',
        'fa-spin', 'fa-spin-pulse', 'fa-pulse', 'fa-spin-reverse',
        'fa-rotate-90', 'fa-rotate-180', 'fa-rotate-270', 'fa-rotate-by',
        'fa-flip', 'fa-flip-horizontal', 'fa-flip-vertical', 'fa-flip-both',
        'fa-beat', 'fa-fade', 'fa-beat-fade', 'fa-bounce', 'fa-shake',
        'fa-border', 'fa-inverse', 'fa-li', 'fa-ul', 'fa-swap-opacity', 'fa-width-auto', 'fa-width-fixed',
        'fa-pull-left', 'fa-pull-right', 'fa-pull-start', 'fa-pull-end',
    ];

    /** @var array<string, ResolvedFontAwesomeIcon|false> */
    private static array $cache = [];
    /** @var array{aliases: array<string, string>, shims: array<string, array{name: string, style: ?string}>}|null */
    private static ?array $legacyNames = null;

    public function resolve(string $classes): ?ResolvedFontAwesomeIcon
    {
        if (!\array_key_exists($classes, self::$cache)) {
            self::$cache[$classes] = $this->doResolve($classes) ?? false;
        }

        return false === self::$cache[$classes] ? null : self::$cache[$classes];
    }

    private function doResolve(string $classes): ?ResolvedFontAwesomeIcon
    {
        $tokens = preg_split('/\s+/', trim($classes), -1, \PREG_SPLIT_NO_EMPTY);

        $requestedStyle = null;
        $iconNames = [];
        foreach ($tokens as $token) {
            if (\in_array($token, self::PRO_CLASSES, true) || $this->hasProClassPrefix($token)) {
                return null;
            }

            if (null !== $style = self::STYLE_CLASSES[$token] ?? null) {
                if (null !== $requestedStyle && $style !== $requestedStyle) {
                    return null;
                }

                $requestedStyle = $style;

                continue;
            }

            if (\in_array($token, self::FAMILY_CLASSES, true) || $this->isModifierClass($token) || !str_starts_with($token, 'fa-')) {
                continue;
            }

            $iconNames[] = substr($token, 3);
        }

        if (1 !== \count($iconNames)) {
            return null;
        }

        $iconName = $iconNames[0];
        if (1 !== preg_match('/^[a-zA-Z0-9_-]+$/D', $iconName)) {
            return null;
        }

        if (null === $resolved = $this->findIcon($iconName, $requestedStyle)) {
            return null;
        }

        [$style, $canonicalName, $path] = $resolved;
        $svgContents = @file_get_contents($path);
        if (!\is_string($svgContents)) {
            return null;
        }

        if ($canonicalName !== $iconName) {
            $tokens[] = 'fa-'.$canonicalName;
        }

        return new ResolvedFontAwesomeIcon($style, $canonicalName, $path, $svgContents, $tokens);
    }

    /**
     * Without an explicit style class, the icon names are treated as in the
     * FontAwesome 4 compatibility CSS: legacy names are looked up first,
     * because some of them use another style (e.g. 'fa fa-credit-card' is
     * the regular icon and 'fa fa-github' is the brands icon).
     *
     * @return array{FontAwesomeStyle, string, string}|null the style, the icon name and the SVG file path
     */
    private function findIcon(string $iconName, ?FontAwesomeStyle $requestedStyle): ?array
    {
        $legacyNames = $this->getLegacyNames();
        $shim = $legacyNames['shims'][$iconName] ?? null;

        if (null === $requestedStyle && null !== $shim) {
            $shimStyle = null === $shim['style'] ? FontAwesomeStyle::Solid : FontAwesomeStyle::from($shim['style']);

            return $this->findIconFile($shim['name'], $shimStyle);
        }

        $style = $requestedStyle ?? FontAwesomeStyle::Solid;
        foreach ([$iconName, $legacyNames['aliases'][$iconName] ?? null, $shim['name'] ?? null] as $candidateName) {
            if (null !== $candidateName && null !== $icon = $this->findIconFile($candidateName, $style)) {
                return $icon;
            }
        }

        return null;
    }

    /**
     * @return array{FontAwesomeStyle, string, string}|null
     */
    private function findIconFile(string $iconName, FontAwesomeStyle $style): ?array
    {
        $path = sprintf('%s/%s/%s.svg', self::ICONS_DIR, $style->value, $iconName);

        return is_file($path) ? [$style, $iconName, $path] : null;
    }

    /**
     * @return array{aliases: array<string, string>, shims: array<string, array{name: string, style: ?string}>}
     */
    private function getLegacyNames(): array
    {
        return self::$legacyNames ??= require self::ICONS_DIR.'/aliases.php';
    }

    private function hasProClassPrefix(string $class): bool
    {
        foreach (self::PRO_CLASS_PREFIXES as $prefix) {
            if (str_starts_with($class, $prefix)) {
                return true;
            }
        }

        return false;
    }

    private function isModifierClass(string $class): bool
    {
        return \in_array($class, self::MODIFIER_CLASSES, true)
            || 1 === preg_match('/^fa-(\d+x|stack(-\d+x)?)$/D', $class);
    }
}
